### ISSUE TITLE
Usage examples for eon.py

### ISSUE THREAD

**Issue by roflcoopter** [erijo/energy-utils#1]
Hello! 

I am really interested in using your solution of gathering information from eon, but I'm having a bit of a hard time understanding the library.

I would like to extract the hour by hour based data.

I managed to get get_month_import to work, but how should i interpret the data returned?
A snippet of what i get in return is:
`[(200, 200, 200, 160, 220, 170, 190, 240, 210, 140, 190, 170, 170, 170, 200, 150, 200, 180, 280, 400, 360, 480, 500, 400), (210, 180, 210, 170, 210, 160, 210, 180, 530, 460, 210, 950, 440, 290, 280, 320, 750, 1300, 430, 970, 410, 1220, 1120, 650),`

Does each item in the list represent one day, and each value in the tuple is the consumption per hour?
What unit is this in?

**Comment by erijo** [comment]
Yes, that is correct. The unit is Wh.

**Comment by roflcoopter** [comment]
Great, thanks!

Whats the difference between the import and export function? The import one seems to do what i need, just curious

**Comment by erijo** [comment]
Export is when you sell energy, import when you buy.

**Comment by erijo** [comment]
See the eon2pvoutput script for some example usage.

**Comment by roflcoopter** [comment]
I see.

Thanks for the clarification and a great library!
